### ISSUE TITLE
Theme Options/Template Options or the sidebar position(left or right)

### ISSUE THREAD

**Issue by mjteves1986** [bassjobsen/jbst#104]
Hello Mr. Bass,

I was wondering, if I change the template options in every pages, and select left sidebar layout. The left sidebar is not appear. only detect correct is "full-width" and "right-sidebar".  I download a plugin "Options Framework" to use the themes Option menu on admin and select left sidebar on all page. but still not working.

I try to use this on page.php

global $jbst_layout;
$jbst_layout = 'full-width';

But still not working on if I set into left-sidebar( $jbst_layout = 'left-sidebar'; ) 
Hope you can help me Mr. Bass,

Thanks,
Mark

**Comment by bassjobsen** [comment]
Hi Mark,

Thanks for posting this issues. I found some issues for this indeed. Please try the latest version and, let me know this fixed it.

With the latest version you should can set:
-layout per page
-layout per type (if theme options framework enabled)

Defining the layout in your templates should also be possible:

```
global $jbst_layout;
$jbst_layout = 'full-width';
```

At the moment the homepage (is not set to a static page) seems to be a special case. It gets a `right-sidebar` by default. Cause it is not a page you can't not change it if the options framework isn't enable. With the  options framework enable the home page got the "default page layout".

In the case you create a home.php or front-page.php template you can use:

```
global $jbst_layout;
$jbst_layout = 'full-width';
```

Or define in function.php:

```
function jbst_set_layout_home_page()
{
    if(is_home() || is_front_page())
    {
    global $jbst_layout;
    $jbst_layout = 'three-column';
    }
}   
add_action( 'wp_head', 'jbst_set_layout_home_page');
```

**Comment by ghost** [comment]
New theme update solved widget issues for me.
(My  front page has no concern of this because of custom markup).
