### ISSUE TITLE
updating master theme

### ISSUE THREAD

**Issue by ghost** [bassjobsen/jbst#107]
Hello,
just tried to update the theme by replacing files.
Big error message showing: 

<pre> /library/assets/less/custom.less is missing'); } } return array(str_replace(ABSPATH,'',$customless));     } add_filter( 'get_theme_mods','get_theme_mods_live'); function get_theme_mods_live() { ob_start();     require_once( get_template_directory() . '/functions/custom-style.php' );     do_action('jbst_add_to_custom_style'); $return = ob_get_contents (); ob_clean(); if(get_theme_mod('container_width')=='980') $return .= '@media (min-width: 1200px) { .container { max-width: 970px; } }'; if(get_theme_mod('gridfloatbreakpoint','768')=='0') { $return .= '@grid-float-breakpoint:0; @grid-float-breakpoint-max:0;'; } elseif(get_theme_mod('gridfloatbreakpoint','768')=='992') { $return .= '@grid-float-breakpoint:992px; @grid-float-breakpoint-max:991px;'; } else { $return .= '@grid-float-breakpoint:768px; @grid-float-breakpoint-max:767px;'; } return $return; } function lesscustomize($setting) { $updatecss = WP_LESS_to_CSS::$instance; $updatecss->wpless2csssavecss(unserialize(get_theme_mod('customizercredits'))); } function deletestoredcredits() { remove_theme_mod( 'customizercredits' ); }     add_action('wp_login','deletestoredcredits' ); add_action( 'customize_save_after', 'lesscustomize' ); function jbst_tmpadminheader() { /** * Dashboard Administration Screen * * @package WordPress * @subpackage Administration */ /** Load WordPress Bootstrap */ require_once(ABSPATH . 'wp-admin/admin.php' ); /** Load WordPress dashboard API */ require_once(ABSPATH . 'wp-admin/includes/dashboard.php'); wp_dashboard_setup(); wp_enqueue_script( 'dashboard' ); if ( current_user_can( 'edit_theme_options' ) ) wp_enqueue_script( 'customize-loader' ); if ( current_user_can( 'install_plugins' ) ) wp_enqueue_script( 'plugin-install' ); if ( current_user_can( 'upload_files' ) ) wp_enqueue_script( 'media-upload' ); add_thickbox(); if ( wp_is_mobile() ) wp_enqueue_script( 'jquery-touch-punch' ); $title = __('Customizer credentials','jamedo-bootstrap-start-theme'); $parent_file = 'index.php'; include( ABSPATH . 'wp-admin/admin-header.php' ); }    function storecedits( $wp_customize ) { if(! WP_Filesystem(unserialize(get_theme_mod('customizercredits')))) { ob_start();  $in = true; $url = 'customize.php'; if (false === ($creds = request_filesystem_credentials($url, '', false, false,null) ) ) { $in = false; $form = ob_get_contents(); ob_end_clean(); jbst_tmpadminheader(); echo $form; require( ABSPATH . 'wp-admin/admin-footer.php' ); exit; } ob_end_clean(); if ($in && ! WP_Filesystem($creds) ) { // our credentials were no good, ask the user for theme again jbst_tmpadminheader(); request_filesystem_credentials($url, '', true, false,null); require( ABSPATH . 'wp-admin/admin-footer.php' ); $in = false; exit; } set_theme_mod('customizercredits', serialize($creds)); } } add_action('customize_controls_init', 'storecedits', 1);</pre>

The whole WP installation show this, and french special characters are replaced by random others.

**Comment by bassjobsen** [comment]
Does the error show any line number?
Did you use the latest version or did you pick one of the releases from: https://github.com/bassjobsen/jamedo-bootstrap-start-theme/releases

**Comment by bassjobsen** [comment]
in function/jbst-less-function.php the action hook shown below is add:

```
add_filter( 'add_extra_less_files', 'add_extra_less_files_live');
function add_extra_less_files_live()
{
    if(!file_exists($customless=get_stylesheet_directory().'/less/custom.less'))
    {
        if(!file_exists($customless=get_template_directory().'/library/assets/less/custom.less'))
        {

          wp_die('<strong>/library/assets/less/custom.less</strong> is missing');

        }
    }  
    return array(str_replace(ABSPATH,'',$customless));    
}
```

It seems your code end up in the `wp_die()`, could you confirm `/library/assets/less/custom.less` exists in your situation? (In fact this file will be empty if you make use of child themes)

**Comment by bassjobsen** [comment]
I found your issue and will provide you a fix a.s.a.p.

**Comment by bassjobsen** [comment]
Please download the latest version (or add `<?php` in stead of `<?` at the beginning of functions/jbst-less-functions.php). The error you mentioned was caused by an accidental short code, see http://www.php.net/manual/en/language.basic-syntax.phptags.php

**Comment by ghost** [comment]
Ok, done, everyhting fine. I just had to recompile less.

2014-02-10 12:05 GMT+01:00 Bass Jobsen notifications@github.com:

**Comment by bassjobsen** [comment]
nice. Indeed you have always to recompile after an update.
