### ISSUE TITLE
[question] Why using filters when setting Bootstrap classes?

### ISSUE THREAD

**Issue by thednp** [bassjobsen/jbst#116]
Why not just create a theme that already have them and minimize the PHP queries?

**Comment by bassjobsen** [comment]
@thednp thanks for your question. I'm interested in all solutions which can make JBST better.

Are you referring to the filters which set:

`<div id="content" role="main" class="site-content <?php echo apply_filters('jbstmaingridclass',jbst_content_span()) ?>">`

The grid class set the way the grids act responsive. For instance when the xs (extra small) grid will be chosen the grid columns will never be stack and always horizontal. These setting also play in solving issues like https://github.com/bassjobsen/jamedo-bootstrap-start-theme/issues/86

Any suggestions are welcome.

**Comment by thednp** [comment]
Thanks for reply my fiend, I think I am making a small confusion while checking multiple free themes at the same time.

I've checked Roots as well as Shoestrap (forked from Roots) and other themes and noticed they use alot of filters to change the HTML mark-up. More examples of such filters here:
https://github.com/cassler/WP-Bootstrap-Transformer

About making jamedo more functional and more interesting I would advise using Vafpress Framework over any other, it offers a great deal of  features and the development version includes already new features, it's amazing, check it out:
https://github.com/vafour/vafpress-framework

**Comment by bassjobsen** [comment]
I have checked Vafpress Framework. Seems a solid framework. At the moment i don't see much added value in reference to what JBST alsready has to offer. I like the idea of offering the core as a plugin, i wil consider that for the next version of JBST too.
