### ISSUE TITLE
Theme customizer not working

### ISSUE THREAD

**Issue by quokka** [bassjobsen/jbst#12]
Hi Bass,

Great work, thanks for this nice starter theme!

I was playing with it but it seems the theme customizer is not working (no css in preview)..

![image](https://f.cloud.github.com/assets/1666461/988217/2245e720-08fd-11e3-8dde-0b7d2138ff4d.png)

Had a look but can't figure it out..
Thanks!
Bas

**Comment by quokka** [comment]
Sorry..
It's a plugin conflict!

**Comment by bassjobsen** [comment]
Hi Bas, Thanks for trying. I'm looking forward to your feedback. Please add all issues you find. For now realize it's based on Twitter's Bootstrap RC2. With the final release of Twitter Bootstrap 3 this theme will become ready for production. Regards, Bass

**Comment by quokka** [comment]
Hi Bass,
I will be watching this project close, think it has all that a good WP
framework must have. I've been looking out for such a framework for a long
time..

If i find any issues I'll let you know..

Thanks again!!!
Bas
