### ISSUE TITLE
search navbar won't work

### ISSUE THREAD

**Issue by bassjobsen** [bassjobsen/jbst#2]
if I click the search bar, it will redirect into "sample page"

**Comment by bassjobsen** [comment]
The navbar item(s) seems to overlap the search box. CSS have to be changed to fit TB3.

**Comment by mjteves1986** [comment]
This what I add on my css childtheme to fix the issue:
@media (min-width: 768px) and (max-width: 1920px) { 
    .nav-collapse.collapse {  float: left; }
}
@media (max-width: 685px) {  
    .navbar-toggle { z-index: 10; }
}
@media (max-width: 600px) {  
    .right-buttons #nav-profile-dropdown a { display: none;}
}

**Comment by bassjobsen** [comment]
Hi Mark,

Thanks. I will migrate the bootstrap css for the navbar soon and keep your fixes in mind.

**Comment by bassjobsen** [comment]
i have done futher migration of the navbar, based on http://www.bootply.com/bootstrap-3-migration-guide. This should fix the problem with the navbar.
I found many media queries for the navbar i wonder if we will need them with TB3
