### ISSUE TITLE
Footer widgets not under "Appearance > Widgets"

### ISSUE THREAD

**Issue by quokka** [bassjobsen/jbst#21]
tried on 2 installs
my footer widgets are visible in frontend..

But under "Appearance > Widgets" they are missing.
only the Left Content Sidebar and Right Content Sidebar show up..

Thanks!
Bas

**Comment by quokka** [comment]
Hi Bass,

After investigating I found that no sidebars are registered for the footer widget areas.

I created a function to do that and use in in my child theme's functions.php

I don't know how to contribute by github but adding this code to functions/template-sidebars.php would do the trick.

It automatically registers the appropriate number of footer widgets / sidebars..

```
/* Call function to register footer sidebars / widget areas */
add_action( 'widgets_init', 'skematik_footer_widgets_init' );

function skematik_footer_widgets_init() {
    $ftr_widgets = get_theme_mod( 'footer_widgets_number', 4 );

    $footer_widgets_array = array(
        "1" => "One",
        "2" => "Two",
        "3" => "Three",
        "4" => "Four",
    );

    for ( $i=0; $i < $ftr_widgets; $i++ ) {
        register_sidebar( array(
            'name' => __( 'Footer Widget '.$footer_widgets_array[$i].'', 'jamedo-bootstrap-start-theme'),
            'id' => 'footer-widget-'.strtolower($footer_widgets_array[$i]).'',
            'before_widget' => '<p>',
            'after_widget' => "</p>",
            'before_title' => '<h4>',
            'after_title' => '</h4>',
        ) );

    }
}
```

**Comment by fibasile** [comment]
Your fix contains an error, the array index starts from 0. This way it works perfectly:

```
/* Call function to register footer sidebars / widget areas */
add_action( 'widgets_init', 'skematik_footer_widgets_init' );

function skematik_footer_widgets_init() {
    $ftr_widgets = get_theme_mod( 'footer_widgets_number', 4 );

    $footer_widgets_array = array(
        "0" => "One",
        "1" => "Two",
        "2" => "Three",
        "3" => "Four",
    );

    for ( $i=0; $i < $ftr_widgets; $i++ ) {
        register_sidebar( array(
            'name' => __( 'Footer Widget '.$footer_widgets_array[$i].'', 'jamedo-bootstrap-start-theme'),
            'id' => 'footer-widget-'.strtolower($footer_widgets_array[$i]).'',
            'before_widget' => '<p>',
            'after_widget' => "</p>",
            'before_title' => '<h4>',
            'after_title' => '</h4>',
        ) );

    }
}
```

**Comment by quokka** [comment]
Hi Fiore...

> Oops, that hurts... ;-D

Shame one me...
Thanks

Bas

**Comment by bassjobsen** [comment]
Hi Bas and Fiore,

Thank you very much for your contributions. I'm very happy with it!
I update the code already.

@quokka contribute your code via github is easy:
1) lookup the file and choose edit (the project will forked for you)
2) make your changes
3) when saving you changes, you will asked to ask for pull request. (yes indeed)

Best regards,

Bass

**Comment by quokka** [comment]
Hi Bass,

Thanks for the info, if I find some other things I can contribute I will do that with a pull request..

Thanks!
Bas
