### ISSUE TITLE
Logo outside navbar floats to left of page - fix

### ISSUE THREAD

**Issue by quokka** [bassjobsen/jbst#37]
Hi Bass,

Found an issue.
When setting logo config to be shown outside nav, the logo floats on left of the page..

In library/core.php, change:
bloginfo('name')

To:
get_bloginfo('name')

And the issue is fixed..

Regards,
Bas

Ps: I'm not yet into pull requests, will figure that out later ;-)

**Comment by bassjobsen** [comment]
Thanks!
