### ISSUE TITLE
Footer Width

### ISSUE THREAD

**Issue by mjteves1986** [bassjobsen/jbst#6]
I found that if I change the footer width into "Container Width"(default is Full Width) on Customize Admin, the footer padding is not right on max 685px view.

I found the cause. 
if(get_theme_mod( 'footer_width', 'full-width' ) == 'cont-width') {
    echo 'footer.site-footer {padding:15px 0;}';
}

This code is compatible for desktop mode and not on small device.

**Comment by bassjobsen** [comment]
Thanks. I have removed this line for now
