### ISSUE TITLE
short codes example, support and documentation links

### ISSUE THREAD

**Issue by bassjobsen** [bassjobsen/jbst#67]
The links in the short code editor including the demo button won't work or point to old resources.

**Comment by 3rdBardo** [comment]
Hi,

I just noticed that the Shortcodes button currently uses the old TB2 classes, instead of the TB3. I notice that these can be changed in:

jamedo-bootstrap-start-theme-master/library/shortcodes/lib/template-shortcodes.php 

Line 160, should be changed from "row-fluid" to "row"
Line 177, should be changed from "span". to "col-md-"

Tweaking these, I find that my version of these 2 shortcodes now work. I hope this helps.

**Comment by bassjobsen** [comment]
@3rdBardo thank you very much, feel free to do a pull request next time.

**Comment by 3rdBardo** [comment]
Hi Bass,

```
 Thanks for the fix - I'm new to github and never really used it 
```

before (other than looking for things). I'll Google how to do a pull 
request.

```
 Also, I've noticed that the shortcodes used actually come straight 
```

from the Shortcodes Ultimate plugin. At the moment, if you try and 
install this plugin together on the theme every thing will break. The 
plugin function has been declared twice, so it's not going to work.

```
 Wouldn't it be easier to suggest using the Shortcodes Ultimate 
```

plugin (under the main Welcome page), and detecting if it's installed? 
The SU plugin has changed a lot since the version which is theme code is 
based on.

Cheers,

Zain

**Comment by bassjobsen** [comment]
Hi Zain,

Thanks for your suggestion. I like the idea of a separate plugin for Bootstrap's short codes.
Shortcodes Ultimate provides their own set short codes i don't know if these are compatible with TB3 and so JBST.

JBST should provide short codes for Bootstrap's css and components. So we will have 3 option i think.

1) use Shortcodes Ultimate where JBST Bootstrap's code
2) fix the current build in short codes
3) a new plugin like Shortcodes Ultimate for TB3

Please also read: http://skematiktheme.com/support_doc/removing-the-shortcode-library/

Regards,

Bass

**Comment by 3rdBardo** [comment]
Hi Bass,

```
 Shortcodes Ultimate uses it's own CSS and none of the TB3 ones. 
```

They do, however, get the job done if you don't have access to writing 
your own shortcodes! :)

```
 Worthwhile checking out the SU4 interface - it's quite nice and 
```

much more user friendly than the previous version.

```
 I've been looking at some other themes and noticed that some of 
```

them provide "add-on plugins" that you activate to extend functionality. 
e.g. "portfolio and shortcodes" in the free Virtue theme 
(http://wordpress.org/themes/virtue). I think that's option 3 on your list.

```
 Anyway, have a good weekend.
```

Cheers,

Zain

**Comment by bassjobsen** [comment]
I also found something like this: http://bootstrapwpplugin.com/.

**Comment by 3rdBardo** [comment]
I found this: http://wordpress.org/plugins/easy-bootstrap-shortcodes/ 
free(r)... but not tested it just yet. :)

**Comment by bassjobsen** [comment]
Hi Zain,

That plugin looks also great.
It also seems to be easy to add the current shortcodes to Shortcodes Ultimate, see: https://github.com/bassjobsen/twitterbootstrap-shortcodes-ultimate (to test with JBST, install this plugin and  Shortcodes Ultimate, disable the current shortcodes http://skematiktheme.com/support_doc/removing-the-shortcode-library/)

Now the big question will be, should JBST has build in shortcodes or should it only support some plugins (maybe all three mentioned here) just like we support WooCommerce or BBPress.

Regards,

Bass

**Comment by 3rdBardo** [comment]
Hi Bass,

```
 Good question! Personally, I tend to go with the KISS rule and try 
```

to keep things as simple as possible...

```
 From what I can see, probably the first thing is to get the theme 
```

working correctly - so getting things like the headers, layout and 
content areas just right, and really aiming to focus on the project one 
step at a time. The shortcodes are "nice to have's", but probably 
something that could be built in properly, at a later date.

```
 If that's the approach taken, then it would make sense to support 
```

the SU and EBS plugins (just like the WooCommerce and BBPress for the 
moment). Doing so would reduce the number of issues (as it's the 
optional extras that can cause scope-creep on a project).

```
 I personally like to keep themes and functionality separate, and 
```

simplify things - mainly as the more things get built in, the more 
potential issues can come up. Ensuring that a theme "just works" also 
means that a user can add plugins without worrying that their site will 
break, or is incompatible with an essential plugin that they're using 
(I'm sure you've been there!).

```
 That's just my view... Maybe it would be an idea to open up 
```

discussion and see what other people think?

```
 Just to let you know - I've only just started looking into TB3, so 
```

am a little green when it comes to using it. I'm currently playing with 
it, and seeing if I can build a WP theme using this framework. I've 
built a few custom WP themes before, but never a responsive one... it's 
pretty fun so far! :)

Cheers,

Zain
