### ISSUE TITLE
flexslider extension

### ISSUE THREAD

**Issue by bassjobsen** [bassjobsen/jbst#75]
test the flexslider extension with JBST, see also:
http://skematiktheme.com/shop/skematik-flexslider/
and http://skematiktheme.com/forums/topic/some-issues-for-skematic/

Also consider Bootstrap's slideshow component http://getbootstrap.com/javascript/#carousel (should we add this to the short codes).

Will this question be related to the jumbotron (see issue #43 )

**Comment by bassjobsen** [comment]
I wrote a new slider extension / plugin based on Twitter's Boostrap's carousel, see: https://github.com/bassjobsen/twitter-bootstrap-slider. This should replace the flex slider extension (http://skematiktheme.com/forums/forum/extensions/flexslider-extension/).
Again raise the question (see also: https://github.com/bassjobsen/jamedo-bootstrap-start-theme/issues/67), should we bundle this extension or only support it?

**Comment by gegere** [comment]
The twitter bootstrap slider to use on WordPress looks pretty straight forward vs the "flex slider extension". Personally I have started using Royal Slider on my projects.

**Comment by bassjobsen** [comment]
@gegere thanks for your feedback. I will look to  Royal Slider soon. Did you find any troubles with Royal Slider and JBST till now?
What is your opion about bundle some extensions with JBST or only support them?
With support i mean (you will have to install it your self and JBST only fix problems when using them).
Support will make user more flexible in this slider case you could choose between Royal Slider, Flex slider and the new plugin mentioned above.
Bundle some extensions will make install more easy i think.

**Comment by bassjobsen** [comment]
Now offers support for:
- [Twitter Bootstrap Slider](https://github.com/bassjobsen/twitter-bootstrap-slider),recommended! 
- [Royal Slider](http://dimsemenov.com/plugins/royal-slider/wordpress/)
- [Flex Slider](http://www.fergusweb.net/software/flex-slider/)

**Comment by gegere** [comment]
@bassjobsen sorry for my delay. I just started using your theme and Royal Slider together several months ago. 

What is my opinion with bundling some extensions with JBST or only support them? I think out of the gate there is quite a bit learn with any WordPress theme. I didn't know many features were includes in the current build until recently (after several months of development. I think having a short list of tested sliders is the best path to choose.

Stay at it good job!

**Comment by bassjobsen** [comment]
@gegere thanks for your constructive response!
For the moment we indeed start to test (and support) third party plugins and not bundle them. See also the updated README. Royal Slider testing depends on you finding only now, so please let me know if you find any issue.
