### ISSUE TITLE
How do I install this in the header?

### ISSUE THREAD

**Issue by ghost** [bassjobsen/jbst#97]
I'd like to try the following on my site:

http://sumome.com/

Where do I find/edit the header file?

**Comment by bassjobsen** [comment]
Hi Mark,

Thanks for your question.
JBST has it's own template system. There are no header files.

You will find the header function and hooks in functions/jbst-header-functions.php (hook are also describe in the comments of header.php).

You add your code, add the php code shown below in your functions.php file:

```
function load_sumo()
{
    ?>
    <script src="//load.sumome.com/" data-sumo-site-id="93414add2c22c22a1a68495bd3e1478b0ea4957ea2a07d2488e11fe3cde8d2e7" async></script>
    <?php
}   


add_action('jbst_head','load_sumo');
```
